# Generated by Django 3.2.9 on 2022-05-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20220520_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='status',
            new_name='read',
        ),
    ]
