# Generated by Django 3.2.9 on 2022-01-04 15:23

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=image.models.get_file_path),
        ),
    ]
