# Generated by Django 3.2.9 on 2022-04-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_image'),
        ('image', '0002_recipeimage_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
