# Generated by Django 3.2.9 on 2022-01-07 15:49

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20220104_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to=image.models.get_file_path),
        ),
    ]
