# Generated by Django 3.2.9 on 2022-05-19 13:49

from django.db import migrations, models
import django.db.models.deletion
import media_library.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25)),
                ('depth', models.IntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media_library.folder')),
            ],
        ),
        migrations.CreateModel(
            name='FolderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=media_library.models.get_file_path)),
                ('name', models.TextField(max_length=25)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_library.folder')),
            ],
        ),
    ]
