# Generated by Django 3.2.9 on 2022-04-16 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import media_library.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=media_library.models.get_file_path)),
                ('name', models.TextField(max_length=50)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_library.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
