# Generated by Django 3.2.9 on 2022-04-17 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0004_remove_folderimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderimage',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media_library.folder'),
        ),
    ]
