# Generated by Django 3.2.9 on 2022-04-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0006_alter_folderimage_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.TextField(max_length=25),
        ),
        migrations.AlterField(
            model_name='folderimage',
            name='name',
            field=models.TextField(max_length=25),
        ),
    ]
