# Generated by Django 3.2.9 on 2022-04-12 17:46

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]


