# Generated by Django 3.2.9 on 2022-04-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
