# Generated by Django 3.2.9 on 2021-12-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recipesinlist',
            old_name='list_id',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='recipesinlist',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
