# Generated by Django 3.2.9 on 2022-04-27 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('OFFENSIVE', 'OFFENSIVE_CONTENT'), ('UNRELATED', 'UNRELATED_CONTENT'), ('OTHER', 'OTHER')], default='OFFENSIVE', max_length=20)),
                ('desc', models.TextField(max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CLOSED', 'CLOSED'), ('REMOVED', 'REMOVED')], default='PENDING', max_length=10)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_reports', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
