# Generated by Django 3.2.9 on 2022-04-28 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('OFFENSIVE_CONTENT', 'OFFENSIVE_CONTENT'), ('UNRELATED_CONTENT', 'UNRELATED_CONTENT'), ('OTHER', 'OTHER')], default='OFFENSIVE_CONTENT', max_length=20),
        ),
    ]
