# Generated by Django 3.2.9 on 2021-12-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
