# Generated by Django 3.2.9 on 2022-03-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20220219_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
    ]
