# Generated by Django 3.2.9 on 2021-12-02 13:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredients', to='recipe.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
