# Generated by Django 3.2.9 on 2022-04-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipe_hit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='hit_count',
        ),
    ]
