# Generated by Django 3.2.9 on 2022-04-02 14:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_remove_recipe_hit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='course',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
