# Generated by Django 3.2.9 on 2022-04-15 15:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_recipe_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10000, null=True),
        ),
    ]
