# Generated by Django 3.2.9 on 2022-04-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_recipe_steps'),
    ]

    operations = [
        
    ]
