# Generated by Django 3.2.9 on 2022-04-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_recipe_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='desc',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
