# Generated by Django 3.2.9 on 2022-04-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_alter_recipe_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
